[package]
name = "surrealdb-derive"
publish = true
edition = "2021"
version = "0.7.0"
authors = ["Tobie Morgan Hitchcock <tobie@surrealdb.com>"]
description = "Private implementation of procedural macros for surrealdb"
homepage = "https://github.com/surrealdb/surrealdb-derive"
repository = "https://github.com/surrealdb/surrealdb-derive"
keywords = ["surrealdb", "surreal", "database", "derive"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.96"
quote = "1.0.18"
